<?php
/**
 *  This file was generated with crodas/Remember (https://github.com/crodas/Remember)
 *  Do not edit this file.
 *
 */

@foreach ((array)$file as $f) {
if (!is_readable({{@realpath($f)}}) || filemtime({{@realpath($f)}}) > {{filemtime($f)}}) {
    $valid = false;
    return;
}
@end

$data = {{@$data}};
$valid = true;
