<?php
/**
 *  This file was generated with crodas/Remember (https://github.com/crodas/Remember)
 *  Do not edit this file.
 *
 */
$data = unserialize({{@$sData}});

@foreach ((array)$files as $f) {
$file = {{@$f}};
if (!is_readable($file) || filemtime($file) > {{filemtime($f)}}) {
    $valid = false;
    return;
}
@end

$valid = true;
